# -*- coding: utf-8 -*-
"""Kenny_Lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rWdKXRm7PsF2CjMhG2M6j1n36UJDP3zz
"""

import matplotlib.pyplot as plot
import scipy as scp
import numpy as np
import cv2

#3.4.1
coeff = np.array([[3, 1], [1, 2]])
consts = np.array([9, 8])
sol = scp.linalg.solve(coeff, consts)
print("x = ", sol[0])
print("y = ", sol[1])

#3.4.2
def f(x):
  return x**2 + 2*x

res = scp.optimize.minimize_scalar(f)
print("Min: ", res.fun)
print("X @ Min: ", res.x)

#3.4.3
def f_2(x):
  return np.sin(100*np.pi*x) + 0.5*np.sin(160*np.pi*x)

sampling_freq = 1000
samples = 1000
t = np.linspace(0, 1, samples, endpoint=False)
y = f_2(t)
y_fft = scp.fft.fft(y)
freq = scp.fft.fftfreq(samples, 1/sampling_freq)

plot.figure()
plot.plot(freq,np.abs(y_fft))
plot.title("Freq Response")
plot.xlabel("Freq (Hz)")
plot.ylabel("Amplitude")
plot.xlim(0, sampling_freq/2)
plot.grid(True)
plot.show()